[package]
name = "crusoe"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "crusoe"
path = "src/bin/main.rs"

[dependencies]
serde = { version = "1.0.219", features = ["serde_derive"] }
serde_json = "1.0.140"
toml = "0.8.23"
