[package]
name = "crusoe"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "crusoe"
path = "src/bin/main.rs"

[dependencies]
enum_dispatch = "0.3.13"
itertools = "0.14.0"
rand = "0.9.1"
serde = { version = "1.0.219", features = ["serde_derive"] }
serde_json = "1.0.140"
toml = "0.8.23"
